### ISSUE TITLE
Los precios no son correctos

### ISSUE THREAD

**Issue by xkill** [hectorespert/som-energia-hass#1]
Actualizar los precios en función a: https://www.somenergia.coop/es/tarifas-de-electricidad/#tarifa20TD

**Comment by madmalkav** [comment]
@xkill vas a actualizar el pull request con los cambios para el mecanismo de compensación que hiciste en tu fork?

**Comment by hectorespert** [comment]
Que es la compensación?

**Comment by madmalkav** [comment]
Mira en tu factura una línea que pone:

"Importe de la energía asociada al mecanismo ibérico regulado por el Real Decreto-ley 10/2022, de 13 de mayo."

Y la explicación de Som Energía aquí:

https://blog.somenergia.coop/tarifas-electricidad-y-sector-electrico/tarifas-y-precios-de-la-luz/2022/08/actualizacion-de-precios-en-octubre-por-el-mecanismo-de-ajuste-del-gas/

**Comment by xkill** [comment]
No es necesario. Al ser un precio fijo se pone directamente en Home Assistant.

Por cierto. Este pull request no funciona bien, mejor cancelarlo

**Comment by hectorespert** [comment]
@xkill Que PR es el que no funciona?
