### ISSUE TITLE
Este dispositivo no se puede añadir desde la IU

### ISSUE THREAD

**Issue by danielccm** [hectorespert/som-energia-hass#9]
Buenas! Me dice que no puedo añadirlo desde la IU, que "puedes añadir este dispositivo añadiéndolo a tu 'configuration.yaml'. Consulta la documentación para obtener más información."

Help?

**Comment by hectorespert** [comment]
Prueba a instalar una versión anterior y luego actualizarla, cuando saque un rato investigaré.

Gracias por avisar.

**Comment by renatotorcuato** [comment]
Me pasó lo mismo. 
Gracias por la solución y gracias por la extensión.

**Comment by hectorespert** [comment]
He creado una nueva versión con el fix, podéis probarla
